### ISSUE TITLE
Nystrom approximations

### ISSUE THREAD

**Issue by IsakFalk** [theogf/KernelFunctions.jl#19]
It would be nice to include Nystrom approximations if we are to do the same for Random Features, as per #14.

@trthatcher has already put in work here through the archived [MLKernels](https://github.com/trthatcher/MLKernels.jl) in [nystrom.jl](https://github.com/trthatcher/MLKernels.jl/blob/master/src/nystrom.jl) over there. I haven't looked through it in detail, but looks fine to apply here?

**Comment by theogf** [comment]
Yes it would be nice to have it! If you want to submit a PR to transfer the work of @trthatcher that would be amazing!

**Comment by IsakFalk** [comment]
I'm a bit busy with ICML stuff now, but I can look into this after. Or if someone else is interested in tackling this!

**Comment by IsakFalk** [comment]
I've ported the code (thanks @trthatcher!) to work with KernelFunctions. It seems to work but I need to run and add some tests. I'm not really sure what the method `syrk_wrapper!` does and searching doesn't turn up many results. Could also be a leftover from earlier Julia versions?

**Comment by trthatcher** [comment]
It's just an `transpose(A)*A` or `A*transpose(A)` operation. The reference BLAS implementation outlines what it does here:

> http://www.netlib.org/lapack/explore-html/dc/d05/dsyrk_8f_source.html

I implemented Nystrom before there was a lazy transpose, so there was actual overhead for calling either of those operations. Using `transpose` and `mul!` should be fine with Julia 1.0.

Sorry guys! I'm tied up with other obligations, otherwise I'd try to be an active contributor.

**Comment by IsakFalk** [comment]
@trthatcher no worries, thanks for taking time to respond and explaining!

**Comment by IsakFalk** [comment]
Linking to the PR #30

**Comment by IsakFalk** [comment]
Since we merged the #30 I'll mark this issue as resolved.
